baseURL = 'https://vikalpgupta.com/'
languageCode = 'en-us'
title = 'Vikalp, Designer'

[params]
  description = 'Digital product designer working at the intersection of technology & human behaviour'
  author = 'Vikalp Gupta'
  ogImage = '/images/og-image.png'

[menu]
  [[menu.main]]
    name = 'Writing'
    url = '/blog/'
    weight = 1

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']

[[params.socialLinks]]
  name = "Email"
  url = "mailto:contact@vikalpgupta.com"

[[params.socialLinks]]
  name = "Twitter"
  url = "https://twitter.com/vikxlp"

[[params.socialLinks]]
  name = "Mastodon"
  url = "https://tatooine.club/@vikalp"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
